// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.865
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Services() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section id=\"services\" class=\"services-section\"><div class=\"container\"><!-- Hero --><header class=\"services-hero\"><h2>Services</h2><h3>Crafting thoughtful digital solutions — from idea to impact.</h3></header><!-- Intro Text --><div class=\"services-intro-container\"><p>I support purpose-driven teams, creatives, and founders with a mix of hands-on development, strategic thinking, and human-centered design. Whether you need a digital product built from scratch or guidance to refine your idea — I’m here to help.</p></div><!-- Service Offerings --><h4>How I can support you</h4><ul><li><h3>Fullstack Development</h3>Custom web apps, responsive frontends, performant APIs. Technologies I use include React, Node.js, Swift, and more.</li><li><h3>Product Strategy</h3>Clarify your vision, prioritize features, and align user needs with business goals — from MVPs to mature platforms.</li><li><h3>UX/UI & Prototyping</h3>Simple, honest design that speaks clearly. I help translate complexity into intuitive flows and meaningful interactions.</li><li><h3>Technical Consulting</h3>From architecture choices to ethical tech decisions — I provide insight with a systems-thinking mindset.</li><li><h3>Creative Collaboration</h3>I love working with musicians, artists, and cultural initiatives — helping translate ideas into digital presence.</li></ul><!-- Call to Action --><div class=\"cta\"><p>Curious how we could work together?</p><a href=\"#contact\" class=\"cta-button\">Let’s start a conversation</a></div></div></section>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = BaseHtml().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
